version: '3'

services:

  nginx:
    image: nginx:1.25.4
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8088:80
    depends_on:
      - app
    container_name: megaron_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: megaron_app

  # db:
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: megaron
  #     POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
  #   ports:
  #     - 8888:5432
  #   container_name: megaron_postgres

  db:
    image: mysql:8.3.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: megaron
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8888:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: megaron_mysql

  redis:
    image: redis:7.2.4
    volumes:
      - ./tmp/local-data/:/data
    restart: always
    ports:
      - 8008:6379
    command: redis-server 
    container_name: megaron_redis
  # redis:
  #   image: redis:7.2.4
  #   volumes:
  #     - ./local-data/:/data
  #   restart: always
  #   ports:
  #     - 8008:6379
  #   command: redis-server 
  #   container_name: pj_rd

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret